apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=1.3.0
  # yaml in current directory that configures the awx deployment
  - awx-admin-pass.yaml
  - awx-db-pass.yaml
  - awx-key.yaml
  - persistentVolume.yaml
  - storageClass.yaml  
  - awx-deployment.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 1.3.0

# Specify a custom namespace in which to install AWX
namespace: awx
