apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: awx-postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: awx-projects
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
